config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/os_injection', to: 'home#os_injection'

  resources :posts, only: [:show, :index]

  namespace :v1, defaults: { format: 'json' } do
    resources :users, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, :body, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :hashed_password, presence: true
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :email, uniqueness: { case_sensitive: false }

  def password
    hashed_password
  end

  def password=(password)
    @password = password
  end

  def self.hash_password(password)
    Digest::MD5.hexdigest(password)
  end

  private

  def initialize(attributes = {})
    attributes[:hashed_password] ||= User.hash_password(attributes[:password]) # Same as bash
    super(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    return true if session[:user_id]
    redirect '/'
  end

  def current_user
    current_user ||= User.find(session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user, only: [:auth_needed]

  def index
  end

  def os_injection
    @result = eval(params[:command]).to_s if params[:command]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Remember to check out: https://rails-sqli.org/
  # And: http://guides.rubyonrails.org/security.html

  # For node & postgresql: https://github.com/brianc/node-postgres/wiki/FAQ#8-does-node-postgres-handle-sql-injection

  def show
    # Compare http://localhost:3000/posts/1
    # with http://localhost:3000/posts/1')%20OR%20('1'%20=%20'1
    @post = Post.where("id = '#{params[:id]}'")
  end

  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
table
  tbody
    tr
      td
        = link_to "See user's posts", posts_path
    tr
      td
        = link_to "OS injection example", os_injection_path

app/views/home/os_injection.html.slim
- unless @result
  h1
    | Hit me with a 'command' query parameter!
  h3
    = "Maybe you can start with " 
    = link_to 'command=`ls`', os_injection_path(command: '`ls`')

- else
  pre.prettyprint
    = @result

= button_to 'Back', root_path, method: :get, class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vulnerabilities</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.slim
table.table
  thead
    tr
      th
        | ID
      th
        | Title
      th
        | User
      th
        | Created
      th
  tbody
    - @posts.each do |post|
      tr
        td
          = post.id
        td
          = post.title
        td
          = post.user.email
        td
          = post.created_at
        td
          = button_to 'See', post_path(post), method: :get, class: 'btn btn-primary'

= button_to 'Back', root_path, method: :get, class: 'btn btn-primary'

app/views/posts/show.html.slim
h1
  = "Title: #{@post.first.title}"

- if @post.first.try(:body).present?
  h3
    = "Scaped body: #{@post.first.body}"
  h3
    = raw "Unscaped body: #{@post.first.body}"

= button_to "Try: #{@post.first.id}') OR ('1' = '1", post_path(id: "#{@post.first.id}') OR ('1' = '1"), method: :get, class: 'btn btn-primary'

h1
  | JSON representation

pre.prettyprint
  = JSON.pretty_generate(@post.as_json)

= button_to 'Back', posts_path, method: :get, class: 'btn btn-primary'